server:
  port: 8082
  servlet:
    context-path: /cposition

spring:
    datasource:
        name: test
        url: jdbc:mysql://193.112.105.43:3306/carmonitor?useSSL=false
        username: root
        password: rycuj9_Jian
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    resources:
      static-locations: classpath:/META-INF/resources/
    redis:
      database: 0
      host: 193.112.105.43
      port: 6379
      password: rycuj9
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      timeout: 3000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hro.core.cmanager.dao.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

restfulApi:
    cmanager:
       alarmSet:
          queryInfoByDevid: http://localhost:8081/cmanager/alarmSet/queryInfoByDevid